# Spring Boot Application Name
spring.application.name=Testlytics

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/testlytics_db
spring.datasource.username=myuser
spring.datasource.password=password
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Hibernate (JPA) Configuration

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=JH7LQfY2bNjs9MlxnM5sNdF1XhU7vJ3a
jwt.expiration-in-ms=86400000
